# To Run: conda env create -f environment.yml
name: folk_transformer
channels:
- fastai
- pytorch
- defaults
dependencies:
- pytorch
- fastai==1.0.61
- jupyter
- ipyparallel
- pip
- python==3.7.6
- pip:
  - music21
  - pebble
